#########################################################################################
##############################  MCLarvik configurations  ################################
##################################  Created by Kiwz  ####################################
#########################################################################################
#########################################################################################
######							Commands and Permissions:						   ######
###																					  ###
#		  </mcl reload> <mclarvik.reload> (Reloads all configs and message.txt)			#
#		</mcl update> <mclarvik.update> (Updates all the files in "FilesToCopy")		#
#			   </mcl automsg> <mclarvik.automsg> (Toggle AutoMsg on/off)				#
###																					  ###
#########################################################################################
#########################################################################################

#Auto Message configs.
autoMsgDelayInSec: 300
autoMsgToConsole: false
autoMsgPrefix: '&d[AutoMessage]'

#Your server will FAIL to start if FileDir is not a VALID path!
#Just make the folders before using this plugin.
#If you want to save files in a folder inside your server, you can start with plugins/
#If you want to save files in a folder outside your server, you need to start with C:/whatever/you/like/
FileDir: plugins/MCLarvik/

#If you want to make a list of all your plugins included version.
#Created only upon server start and will be saved to the FileDir.
PluginsList: false

#Time between File copy in minutes (do NOT set this to 0)
AutoFileCopy: false
FileCopyDelayInMin: 60

#What files to copy. I recommend not to copy large files (large > 10MB)
FilesToCopy:
- banned-players.txt
- banned-ips.txt

#New name of the copied files (the order is important)
FilesToSave:
- bans.txt
- bans-ip.txt

#If you want users.txt file that contains group-sorted list of players.
#This will only work if you use bPermission, and is updated same time as FilesToCopy.
GetGroups: false
WorldToGetGroupFrom: world
Groups:
- vip
- mod
- admin

#Date and Time format, see http://docs.oracle.com/javase/1.4.2/docs/api/java/text/SimpleDateFormat.html
TimeFormat: YYYY-MM-dd HH:mm:ss

#List of Commands to log in commands1.txt
UseCmdToLog1: false
CmdToLog1:
- /spawn
- /gamemode

#List of Commands to log in commands2.txt
UseCmdToLog2: false
CmdToLog2:
- /god
- /heal

#List of Private messages to log in private-msg.txt
UsePrivMsgToLog: false
PrivMsgToLog:
- /msg
- /r

#Set to true if you want to log chat to chat.txt
Chat: false

#Set to true if you want to log all Towny chat channels to towny-chat.txt
TownyChat: false

#Set to true if you want to log all [Warning] and [Severe] messages to warning.txt
WarningAndSevere: false

#Set to true if you want to have a xtra real-time copy of the server.log
XtraServerLog: false